    {"cheat:a:CheatEnter", 0x44bd24d473ccebb4ULL}, // 0 bytes; 
    {"cheat:a:CheatAllFree", 0x2e44f15a4fb96f95ULL}, // 431 bytes; 
    {"cheat:a:CheatCrtSpells", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:CheatRevealMap", 0xb7bbeaff1776c341ULL}, // 21664 bytes; 
    {"cheat:a:CheatCrAllSpls", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:CheatAllMagic", 0x9ae0ddd5be241bc7ULL}, // 70 bytes; 
    {"cheat:a:CheatAllRooms", 0xc1fd40effaf57484ULL}, // 60 bytes; 
    {"cheat:a:CheatAllResrchbl", 0xf4a2aa878417339aULL}, // 117 bytes; 
    {"cheat:a:CheatSwitchTerrain 12", 0x0cf4f43789ebb9a4ULL}, // 110 bytes; 
    {"cheat:a:CheatSwitchTerrain 0", 0xb1456fa635fa24b5ULL}, // 109 bytes; 
    {"cheat:a:CheatSwitchPlayer 1", 0x484fc3a635fa24b5ULL}, // 109 bytes; 
    {"cheat:a:CheatSwitchCreature 5", 0x0a33c3bdaeee68fbULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchHero 3", 0x98fca727be61318cULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchExperience 4", 0xcdb6b89408d4e719ULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchTrap 2", 0xb8d4d8f8a59a801bULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchDoor 2", 0xa35de8c9a1dca3c3ULL}, // 56 bytes; 
    {"cheat:a:CheatAllDoors", 0xdea89f8716c4924aULL}, // 59 bytes; 
    {"cheat:a:CheatAllTraps", 0xbe1644d74c0f5d82ULL}, // 60 bytes; 
    {"cheat:a:CheatGiveDoorTrap", 0xe8a7dadf8afff9e9ULL}, // 73 bytes; 
    {"cheat:a:CheatWinLevel", 0xb46e37a2829b7456ULL}, // 74 bytes; 
    {"cheat:a:CheatLoseLevel", 0xbf1cea239355a7adULL}, // 73 bytes; 
    {"cheat:a:CheatLevelUp", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatLevelUp", 0xde7827a071fabc02ULL}, // 38 bytes;  possess=1 ;
    {"cheat:a:CheatLevelDown", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatLevelDown", 0xd5ada2e3629415a0ULL}, // 46 bytes;  possess=1 ;
    {"cheat:a:CheatApplySpell 3", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatApplySpell 3", 0x74566a46551f33eaULL}, // 40 bytes;  possess=1 ;
    {"cheat:a:CheatKillCreature", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatKillCreature", 0x7f5d6320a22bbf28ULL}, // 102 bytes;  possess=1 ;
    {"cheat:a:CheatPlaceTerrain 12 0", 0x4cfd084e773d9bccULL}, // 2190 bytes; 
    {"cheat:a:CheatPlaceTerrain 11 1 @ROOM", 0xeed3279c80219230ULL}, // 1315 bytes; 
    {"cheat:a:CheatPlaceTerrain 0 5 @40,40", 0x916f8ce18a794b12ULL}, // 903 bytes; 
    {"cheat:a:CheatMakeCreature 5 0", 0x1b0679b5a0c62670ULL}, // 123 bytes; 
    {"cheat:a:CheatMakeCreature 5 772", 0xeeb8897527219277ULL}, // 125 bytes; 
    {"cheat:a:CheatMakeCreature 5 4 @40,40", 0x40ad0c7288e8ed76ULL}, // 81 bytes; 
    {"cheat:a:CheatMakeDigger 0 2", 0x2dcd2735bafccd9eULL}, // 123 bytes; 
    {"cheat:a:CheatMakeDigger 1 0", 0xa73664008d8465dbULL}, // 119 bytes; 
    {"cheat:a:CheatStealSlab 11 1", 0xa1e4cb067fed9fb2ULL}, // 2132 bytes; 
    {"cheat:a:CheatStealSlab 11 260", 0xd8951dc2e9d52aafULL}, // 2158 bytes; 
    {"cheat:a:CheatStealSlab 4 260", 0x514cd91a4a87e800ULL}, // 2185 bytes; 
    {"cheat:a:CheatStealSlab 12 0 @40,40", 0xfbd75c0007ef985bULL}, // 652 bytes; 
    {"cheat:a:CheatStealRoom 1 0 @ROOM", 0xccccedffc4a9b3d8ULL}, // 463 bytes; 
    {"cheat:a:CheatStealRoom 4 1 @ROOM", 0xf3a1de6a3a47eb7fULL}, // 708 bytes; 
    {"cheat:a:CheatStealRoom 1 0 @40,40", 0xdcc4a61b41e5ffc9ULL}, // 17 bytes; 
    {"cheat:a:CheatHeartHealth 0 1000", 0xa731dad9e4c4fe37ULL}, // 57 bytes; 
    {"cheat:a:CheatHeartHealth 0 0", 0xcf63ad1eed775319ULL}, // 59 bytes; 
    {"cheat:a:CheatHeartHealth 1 500", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:CheatKillPlayer 0", 0xcf63ad1eed775319ULL}, // 59 bytes; 
    {"cheat:a:CheatKillPlayer 1", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:CheatConvertCreature 4", 0xbbbc0b7a5f9eea65ULL}, // 68 bytes; 
    {"cheat:c:ConvertCreatr ; a:CheatConvertCreature 4", 0x12af6460717e7936ULL}, // 72 bytes;  "" ;
    {"cheat:a:EditorFloodFill 12 0", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:EditorFloodFill 11 0 @40,40", 0x3ecc549097dff448ULL}, // 134447 bytes; 
    {"cheat:a:EditorPlaceObject #120 #128 5 0", 0xa7445b9c6eca723aULL}, // 118 bytes; 
    {"cheat:a:EditorPlaceObject #120 #128 3 0", 0x59cce1d6d05a560cULL}, // 97 bytes; 
    {"cheat:a:EditorPlaceObject #500 #500 5 0", 0x2813a19bf488a591ULL}, // 120 bytes; 
    {"cheat:a:EditorPlaceTrap 1 0", 0x7eb6509f1f8902afULL}, // 99 bytes; 
    {"cheat:a:EditorPlaceTrap 2 0 @40,40", 0x84d94b4ce521e373ULL}, // 53 bytes; 
    {"cheat:a:EditorPlaceDoor 1 0", 0xb278a5ab63699ad9ULL}, // 258 bytes; 
    {"cheat:a:EditorPlaceDoor 1 0 @ROOM", 0xe6d7b3dae23a4cf6ULL}, // 267 bytes; 
    {"cheat:a:EditorToggleDoorLock $C0", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:EditorToggleDoorLock 0", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:EditorUndo $C0", 0xc438365093647343ULL}, // 161 bytes; 
    {"cheat:a:EditorUndo $HEART", 0x3515bdd867b3382dULL}, // 118 bytes; 
    {"cheat:a:EditorUndo 0", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:EditorSetGoldValue $C0 500", 0x9e320231737cff40ULL}, // 55 bytes; 
    {"cheat:a:EditorSetThingPosition #120 #128 $C0 0", 0xb84b2ef35017109eULL}, // 61 bytes; 
    {"cheat:a:EditorPlaceTerrainRect #120 #125 12 0", 0x160aa354c0554e1cULL}, // 96927 bytes; 
    {"cheat:a:EditorRectClearEarth #120 #125", 0x75d43eb24ec8ea19ULL}, // 88502 bytes; 
    {"cheat:a:EditorRectDeleteThings #120 #125", 0x5878cef95cbba63dULL}, // 5783 bytes; 
    {"cheat:a:EditorRectSetOwner #120 #125 1", 0xe8ea52ddf3417cb7ULL}, // 12557 bytes; 
    {"cheat:a:EditorRectSetOwner #120 #125 0 @ROOM", 0x95990d81418aacafULL}, // 20352 bytes; 
    {"cheat:a:EditorRedoCreature #126 #131 5 0", 0x1b0679b5a0c62670ULL}, // 123 bytes; 
    {"cheat:a:EditorRedoDigger #126 #131 0 1", 0x9c2a883a77f9545aULL}, // 122 bytes; 
    {"cheat:a:EditorRedoTrap #126 #131 1 0", 0x7eb6509f1f8902afULL}, // 99 bytes; 
    {"cheat:a:EditorRedoDoor #126 #131 1 0", 0xb278a5ab63699ad9ULL}, // 258 bytes; 
    {"cheat:a:EditorGoSpectator #126 #131", 0x30bacdc0ae490224ULL}, // 139 bytes; 
    {"cheat:c:MkDigger", 0xa4fc544fb1dd6dd6ULL}, // 78 bytes;  "1"
    {"cheat:c:MkDigger click", 0x1278b28c40ca6dc9ULL}, // 148 bytes;  "1"
    {"cheat:c:MkDigger click @40,40", 0x93779fc6a80bc43aULL}, // 143 bytes;  "1"
    {"cheat:c:MkGoodCreatr", 0x2701894f6d2215d4ULL}, // 78 bytes;  "?"
    {"cheat:a:CheatSwitchHero 3 ; c:MkGoodCreatr click", 0x6c228aa3238805c3ULL}, // 188 bytes;  "Archer 1"
    {"cheat:c:MkBadCreatr", 0x223f1f4f6d2215d4ULL}, // 78 bytes;  "?"
    {"cheat:a:CheatSwitchCreature 5 ; a:CheatSwitchExperience 3 ; c:MkBadCreatr click", 0xe7c1850dfee3b425ULL}, // 189 bytes;  "Mountain Dwarf 4"
    {"cheat:c:MkGoldPot", 0xd9c61c65624bd1d1ULL}, // 26 bytes; 
    {"cheat:c:MkGoldPot click", 0x89f68c187553ac39ULL}, // 75 bytes; 
    {"cheat:c:OrderCreatr", 0xa1968a88880e0b83ULL}, // 19 bytes; 
    {"cheat:c:OrderCreatr click", 0x360a16452cafc09dULL}, // 26 bytes; 
    {"cheat:c:OrderCreatr click ; c:OrderCreatr click @ROOM", 0x3bf34c20203f10deULL}, // 48 bytes; 
    {"cheat:c:FreeDestroyWalls", 0x600311f5329d270bULL}, // 18 bytes; 
    {"cheat:c:FreeDestroyWalls click", 0x8ab8e1ada445d99fULL}, // 21 bytes; 
    {"cheat:c:FreeDestroyWalls click @40,40", 0x75aab3ada445d99fULL}, // 21 bytes; 
    {"cheat:c:FreeTurnChicken click", 0xd5892bada445d99fULL}, // 21 bytes; 
    {"cheat:c:FreeCastDisease click", 0xd8378eada445d99fULL}, // 21 bytes; 
    {"cheat:c:FreeCastDisease click @40,40", 0x2e54a4ada445d99fULL}, // 21 bytes; 
    {"cheat:c:StealRoom @ROOM", 0xc749cccdb81fc3efULL}, // 70 bytes;  ""
    {"cheat:c:StealRoom click @ROOM", 0xb1df1f9d052a977bULL}, // 73 bytes;  ""
    {"cheat:a:CheatSwitchPlayer 1 ; c:StealRoom click @ROOM", 0x3b457c5339f1fe28ULL}, // 558 bytes;  "Ok"
    {"cheat:c:DestroyRoom click @ROOM", 0x569a0d29f93b1a35ULL}, // 3232 bytes;  "Ok"
    {"cheat:c:DestroyRoom click", 0x00ef886cdddf81fbULL}, // 3951 bytes;  "Ok"
    {"cheat:c:KillCreatr", 0x715b9988880e0b83ULL}, // 19 bytes; 
    {"cheat:c:KillCreatr click", 0xe19302344233ebeaULL}, // 119 bytes; 
    {"cheat:c:KillCreatr click @40,40", 0x585c3eada445d99fULL}, // 21 bytes; 
    {"cheat:c:ConvertCreatr click", 0x18c82f9d052a977bULL}, // 73 bytes;  ""
    {"cheat:a:CheatSwitchPlayer 4 ; c:ConvertCreatr click", 0xb58345bbe7478ef6ULL}, // 126 bytes;  ""
    {"cheat:c:StealSlab", 0xfb6e49866198904aULL}, // 77 bytes;  ""
    {"cheat:c:StealSlab click", 0xd62b5abc8da057bcULL}, // 80 bytes;  ""
    {"cheat:a:CheatSwitchPlayer 1 ; c:StealSlab click", 0x1dd3ae33c2a379ccULL}, // 119 bytes;  ""
    {"cheat:c:StealSlab click @40,40", 0x693849bc8da057bcULL}, // 80 bytes;  ""
    {"cheat:c:LevelCreatureUp click", 0x1587c93fa9fc0410ULL}, // 23 bytes; 
    {"cheat:c:LevelCreatureDown click", 0x42400983c5536c12ULL}, // 31 bytes; 
    {"cheat:c:LevelCreatureUp click @40,40", 0x213a61ada445d99fULL}, // 21 bytes; 
    {"cheat:c:KillPlayer @HEART", 0x530ba2cdb81fc3efULL}, // 70 bytes;  ""
    {"cheat:c:KillPlayer click @HEART", 0x29ec5a6cc41dcc30ULL}, // 77 bytes;  ""
    {"cheat:c:KillPlayer click", 0x2085fc6cc41dcc30ULL}, // 77 bytes;  ""
    {"cheat:c:HeartHealth @HEART", 0x448c23385b2bff98ULL}, // 70 bytes;  "30000/30000"
    {"cheat:c:HeartHealth click @HEART", 0xb96a4cceaf76ec34ULL}, // 73 bytes;  "30000/30000"
    {"cheat:c:QueryAll", 0x6b427888880e0b83ULL}, // 19 bytes; 
    {"cheat:c:QueryAll click", 0x58e871c46513138cULL}, // 28 bytes; 
    {"cheat:c:CreatrInfoAll click", 0x0cff3d5292da7017ULL}, // 27 bytes; 
    {"cheat:c:MkHappy click", 0x891d9380b118b2e7ULL}, // 22 bytes; 
    {"cheat:c:MkAngry click", 0x28de8680b118b2e7ULL}, // 22 bytes; 
    {"cheat:c:MkAngry click @40,40", 0x906203ada445d99fULL}, // 21 bytes; 
    {"cheat:c:PlaceTerrain", 0x34b26ffbb9385efeULL}, // 77 bytes;  "Impenetrable Rock"
    {"cheat:a:CheatSwitchTerrain 12 ; c:PlaceTerrain click", 0xa2724051d6dc03f5ULL}, // 2256 bytes;  "Lava"
    {"cheat:a:CheatSwitchTerrain 11 ; c:PlaceTerrain click", 0x72b01847d11b7f75ULL}, // 2230 bytes;  "Claimed area"
    {"cheat:c:DestroyThing", 0x58630488880e0b83ULL}, // 19 bytes; 
    {"cheat:c:DestroyThing click", 0x1eaccd092c232e58ULL}, // 130 bytes; 
    {"cheat:c:DestroyThing click @HEART", 0x51b1f0efbc53b11cULL}, // 89 bytes; 
    {"cheat:c:DestroyThing click @40,40", 0xe522a9ada445d99fULL}, // 21 bytes; 
    {"cheat:c:EditorPlaceTerrainRect press @120,125 ; c:EditorPlaceTerrainRect release", 0x199017bcdc8f7f43ULL}, // 3937 bytes; 
    {"cheat:c:EditorRectClearEarth press @120,125 ; c:EditorRectClearEarth release", 0x50966bdcefefc174ULL}, // 3964 bytes; 
    {"cheat:c:EditorRectDeleteThings press @120,125 ; c:EditorRectDeleteThings release", 0x5dfefe2fecb3d57eULL}, // 356 bytes; 
    {"cheat:c:EditorRectSetOwner press @120,125 ; c:EditorRectSetOwner release", 0x31f1e8e6f2d5d52bULL}, // 3284 bytes; 
    {"cheat:c:EditorFill click", 0x9ee26c5ccb467e5eULL}, // 28 bytes; 
    {"cheat:c:EditorPlaceObject click", 0xf142a4daf43ead21ULL}, // 29 bytes; 
    {"cheat:c:EditorEyedropper click", 0x7fc2035ccb467e5eULL}, // 28 bytes; 
    {"cheat:c:EditorStamp click", 0x776fb75ccb467e5eULL}, // 28 bytes; 
    {"cheat:c:EditorQuery click", 0x2f4253daf43ead21ULL}, // 29 bytes; 
    {"cheat:c:EditorPlaceTrap click", 0xd217ab6d0264e6fdULL}, // 58 bytes; 
    {"cheat:c:EditorPlaceDoor click", 0xa678255ccb467e5eULL}, // 28 bytes; 
    {"cheat:c:EditorPlaceDoor click @ROOM", 0x8706965ccb467e5eULL}, // 28 bytes; 
    {"cheat:multiplayer", 0xb02b2ab9e608adbeULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatRevealMap", 0xb02b2ab9e608adbeULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatWinLevel", 0xb02b2ab9e608adbeULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatAllRooms", 0xb02b2ab9e608adbeULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatMakeCreature 5 0", 0x81568a4863224b9cULL}, // 56 bytes; 
    {"cheat:multiplayer ; a:CheatPlaceTerrain 12 0", 0x81568a4863224b9cULL}, // 56 bytes; 
    {"cheat:multiplayer ; a:EditorUndo $C0", 0x81568a4863224b9cULL}, // 56 bytes; 
    {"cheat:multiplayer ; a:EditorRectClearEarth #120 #125", 0x81568a4863224b9cULL}, // 56 bytes; 
    {"cheat:multiplayer ; possess ; a:CheatKillCreature", 0x7dd33d28828a772dULL}, // 35 bytes;  possess=1 ;
    {"cheat:multiplayer ; c:KillCreatr click", 0x187b7b895111781bULL}, // 21 bytes; 
    {"cheat:multiplayer ; c:DestroyThing click @HEART", 0x0adcdb895111781bULL}, // 21 bytes; 
    {"cheat:multiplayer ; a:SetPlyrState 28 0", 0x81568a4863224b9cULL}, // 56 bytes; 
    {"cheat:a:SetPlyrState 28 0", 0x715b9988880e0b83ULL}, // 19 bytes; 
    {"cheat:multiplayer ; a:SetPlyrState 2 1", 0xf4112f77d8e62519ULL}, // 28 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; a:EditorUndo $C0", 0xc438365093647343ULL}, // 161 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; c:DestroyThing click", 0x1eaccd092c232e58ULL}, // 130 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; a:EditorRectDeleteThings #120 #125", 0xe5c3819787167fa8ULL}, // 5784 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; a:EditorUndo $HEART", 0xd7ecd2e30d766f8eULL}, // 119 bytes; 
