    {"cheat:a:CheatEnter", 0x44bd24d473ccebb4ULL}, // 0 bytes; 
    {"cheat:a:CheatAllFree", 0x2e44f15a4fb96f95ULL}, // 431 bytes; 
    {"cheat:a:CheatCrtSpells", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:CheatRevealMap", 0x6fe05b69d8e7a1f7ULL}, // 21664 bytes; 
    {"cheat:a:CheatCrAllSpls", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:CheatAllMagic", 0x10057ad407c0d271ULL}, // 70 bytes; 
    {"cheat:a:CheatAllRooms", 0x411ae2d7a20c3f3aULL}, // 60 bytes; 
    {"cheat:a:CheatAllResrchbl", 0xdad8b362802f8c34ULL}, // 117 bytes; 
    {"cheat:a:CheatSwitchTerrain 12", 0xf02e96753c53497dULL}, // 110 bytes; 
    {"cheat:a:CheatSwitchTerrain 0", 0x41b537781cf218dfULL}, // 109 bytes; 
    {"cheat:a:CheatSwitchPlayer 1", 0x637ae3781cf218dfULL}, // 109 bytes; 
    {"cheat:a:CheatSwitchCreature 5", 0xec575ae480549a36ULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchHero 3", 0xb11c729b9a9a711fULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchExperience 4", 0xe7300d8c512db750ULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchTrap 2", 0x7803a929f52febfeULL}, // 56 bytes; 
    {"cheat:a:CheatSwitchDoor 2", 0x21017ba2a8eed346ULL}, // 56 bytes; 
    {"cheat:a:CheatAllDoors", 0xdc7f45847a61f1e4ULL}, // 59 bytes; 
    {"cheat:a:CheatAllTraps", 0x992bac68069e0accULL}, // 60 bytes; 
    {"cheat:a:CheatGiveDoorTrap", 0x0633a326d91858afULL}, // 73 bytes; 
    {"cheat:a:CheatWinLevel", 0xdadec17e3a3ee8e8ULL}, // 74 bytes; 
    {"cheat:a:CheatLoseLevel", 0xc5db8377db772e3bULL}, // 73 bytes; 
    {"cheat:a:CheatLevelUp", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatLevelUp", 0xd27ea88d4c4f8722ULL}, // 38 bytes;  possess=1 ;
    {"cheat:a:CheatLevelDown", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatLevelDown", 0x77d5148ccdef3968ULL}, // 46 bytes;  possess=1 ;
    {"cheat:a:CheatApplySpell 3", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatApplySpell 3", 0x5cf78ea4c0ac34eaULL}, // 40 bytes;  possess=1 ;
    {"cheat:a:CheatKillCreature", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:possess ; a:CheatKillCreature", 0xc8747323dd42f441ULL}, // 102 bytes;  possess=1 ;
    {"cheat:a:CheatPlaceTerrain 12 0", 0x37dfeaee83b05662ULL}, // 2190 bytes; 
    {"cheat:a:CheatPlaceTerrain 11 1 @ROOM", 0x99a1083b10beeb66ULL}, // 1315 bytes; 
    {"cheat:a:CheatPlaceTerrain 0 5 @40,40", 0xfb3b50d61f70394cULL}, // 903 bytes; 
    {"cheat:a:CheatMakeCreature 5 0", 0x86b7b2a9721298aeULL}, // 123 bytes; 
    {"cheat:a:CheatMakeCreature 5 772", 0x189ba5633333b421ULL}, // 125 bytes; 
    {"cheat:a:CheatMakeCreature 5 4 @40,40", 0x36c81dbbe07d9108ULL}, // 81 bytes; 
    {"cheat:a:CheatMakeDigger 0 2", 0xecf1440acb3cb380ULL}, // 123 bytes; 
    {"cheat:a:CheatMakeDigger 1 0", 0xc364db72600e373dULL}, // 119 bytes; 
    {"cheat:a:CheatStealSlab 11 1", 0xae35387acd5619d4ULL}, // 2132 bytes; 
    {"cheat:a:CheatStealSlab 11 260", 0x02bf3d4bcaca269dULL}, // 2158 bytes; 
    {"cheat:a:CheatStealSlab 4 260", 0xb64638fa6120c462ULL}, // 2185 bytes; 
    {"cheat:a:CheatStealSlab 12 0 @40,40", 0x356a0abc46384a01ULL}, // 652 bytes; 
    {"cheat:a:CheatStealRoom 1 0 @ROOM", 0xe96d4f67632a640aULL}, // 463 bytes; 
    {"cheat:a:CheatStealRoom 4 1 @ROOM", 0x6a7474f3120e2d8dULL}, // 708 bytes; 
    {"cheat:a:CheatStealRoom 1 0 @40,40", 0x163bfa968b88060fULL}, // 17 bytes; 
    {"cheat:a:CheatHeartHealth 0 1000", 0xa0b283aad6643de1ULL}, // 57 bytes; 
    {"cheat:a:CheatHeartHealth 0 0", 0xa0977202b2aea6dfULL}, // 59 bytes; 
    {"cheat:a:CheatHeartHealth 1 500", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:CheatKillPlayer 0", 0xa0977202b2aea6dfULL}, // 59 bytes; 
    {"cheat:a:CheatKillPlayer 1", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:CheatConvertCreature 4", 0x477de861e9cb3ec3ULL}, // 68 bytes; 
    {"cheat:c:ConvertCreatr ; a:CheatConvertCreature 4", 0xd593229e024bfe66ULL}, // 72 bytes;  "" ;
    {"cheat:a:EditorFloodFill 12 0", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:EditorFloodFill 11 0 @40,40", 0x426b4f6ed5296d36ULL}, // 134447 bytes; 
    {"cheat:a:EditorPlaceObject #120 #128 5 0", 0x2e3a488f8c5d499eULL}, // 118 bytes; 
    {"cheat:a:EditorPlaceObject #120 #128 3 0", 0x7043b7ab215ef712ULL}, // 97 bytes; 
    {"cheat:a:EditorPlaceObject #500 #500 5 0", 0xed3a11cfce9427d9ULL}, // 120 bytes; 
    {"cheat:a:EditorPlaceTrap 1 0", 0xaa0ca32e9c7ae989ULL}, // 99 bytes; 
    {"cheat:a:EditorPlaceTrap 2 0 @40,40", 0x68d5734a2b797745ULL}, // 53 bytes; 
    {"cheat:a:EditorPlaceDoor 1 0", 0xc8e41052c8d6628bULL}, // 258 bytes; 
    {"cheat:a:EditorPlaceDoor 1 0 @ROOM", 0x0f971c1f609f477cULL}, // 267 bytes; 
    {"cheat:a:EditorToggleDoorLock $C0", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:EditorToggleDoorLock 0", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:EditorUndo $C0", 0x190372681a002d95ULL}, // 161 bytes; 
    {"cheat:a:EditorUndo $HEART", 0x65bf292a58c8ff89ULL}, // 118 bytes; 
    {"cheat:a:EditorUndo 0", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:EditorSetGoldValue $C0 500", 0x47256353e68ea47eULL}, // 55 bytes; 
    {"cheat:a:EditorSetThingPosition #120 #128 $C0 0", 0xda97c2e1666f7880ULL}, // 61 bytes; 
    {"cheat:a:EditorPlaceTerrainRect #120 #125 12 0", 0x59ac40fa75a56fdcULL}, // 96927 bytes; 
    {"cheat:a:EditorRectClearEarth #120 #125", 0xaa207bab4c459aa5ULL}, // 88502 bytes; 
    {"cheat:a:EditorRectDeleteThings #120 #125", 0x6253bfeef9a873efULL}, // 5783 bytes; 
    {"cheat:a:EditorRectSetOwner #120 #125 1", 0xdc3f6054b03854dfULL}, // 12557 bytes; 
    {"cheat:a:EditorRectSetOwner #120 #125 0 @ROOM", 0x30fe3b0d6875e3fdULL}, // 20335 bytes; 
    {"cheat:a:EditorRedoCreature #126 #131 5 0", 0x86b7b2a9721298aeULL}, // 123 bytes; 
    {"cheat:a:EditorRedoDigger #126 #131 0 1", 0x4a712e5f52c65bf4ULL}, // 122 bytes; 
    {"cheat:a:EditorRedoTrap #126 #131 1 0", 0xaa0ca32e9c7ae989ULL}, // 99 bytes; 
    {"cheat:a:EditorRedoDoor #126 #131 1 0", 0xc8e41052c8d6628bULL}, // 258 bytes; 
    {"cheat:a:EditorGoSpectator #126 #131", 0x5666815872c6e5c2ULL}, // 139 bytes; 
    {"cheat:c:MkDigger", 0xd3d9717ff94fc3c8ULL}, // 78 bytes;  "1"
    {"cheat:c:MkDigger click", 0xecc8f40ccc10b144ULL}, // 148 bytes;  "1"
    {"cheat:c:MkDigger click @40,40", 0x5381bfd0eb19693bULL}, // 143 bytes;  "1"
    {"cheat:c:MkGoodCreatr", 0x1b894e8016cc1b22ULL}, // 78 bytes;  "?"
    {"cheat:a:CheatSwitchHero 3 ; c:MkGoodCreatr click", 0x168d0348adde4829ULL}, // 188 bytes;  "Archer 1"
    {"cheat:c:MkBadCreatr", 0xa1cf3c8016cc1b22ULL}, // 78 bytes;  "?"
    {"cheat:a:CheatSwitchCreature 5 ; a:CheatSwitchExperience 3 ; c:MkBadCreatr click", 0x14f75f289fbdfb57ULL}, // 189 bytes;  "Mountain Dwarf 4"
    {"cheat:c:MkGoldPot", 0xc38561317f47196fULL}, // 26 bytes; 
    {"cheat:c:MkGoldPot click", 0xf465d9b32bf09df0ULL}, // 75 bytes; 
    {"cheat:c:OrderCreatr", 0x1b11b5b921862bd5ULL}, // 19 bytes; 
    {"cheat:c:OrderCreatr click", 0x2d2ed4cfa4f933f4ULL}, // 26 bytes; 
    {"cheat:c:OrderCreatr click ; c:OrderCreatr click @ROOM", 0x5b267353d3da30ffULL}, // 48 bytes; 
    {"cheat:c:FreeDestroyWalls", 0x41bd5f1c38c8156dULL}, // 18 bytes; 
    {"cheat:c:FreeDestroyWalls click", 0x6131523440405b6eULL}, // 21 bytes; 
    {"cheat:c:FreeDestroyWalls click @40,40", 0x0ddc663440405b6eULL}, // 21 bytes; 
    {"cheat:c:FreeTurnChicken click", 0xa5bdec3440405b6eULL}, // 21 bytes; 
    {"cheat:c:FreeCastDisease click", 0xef725b3440405b6eULL}, // 21 bytes; 
    {"cheat:c:FreeCastDisease click @40,40", 0xf7c8f33440405b6eULL}, // 21 bytes; 
    {"cheat:c:StealRoom @ROOM", 0x10898ad6d397a4a1ULL}, // 70 bytes;  ""
    {"cheat:c:StealRoom click @ROOM", 0x25d6b82d2805a018ULL}, // 73 bytes;  ""
    {"cheat:a:CheatSwitchPlayer 1 ; c:StealRoom click @ROOM", 0x91b3d638a31c8a3bULL}, // 558 bytes;  "Ok"
    {"cheat:c:DestroyRoom click @ROOM", 0x3c4760256b85556fULL}, // 3232 bytes;  "Ok"
    {"cheat:c:DestroyRoom click", 0x02dc3d57764926d1ULL}, // 3951 bytes;  "Ok"
    {"cheat:c:KillCreatr", 0x9b106cb921862bd5ULL}, // 19 bytes; 
    {"cheat:c:KillCreatr click", 0xa3dde366fd511c12ULL}, // 119 bytes; 
    {"cheat:c:KillCreatr click @40,40", 0xc7ce4d3440405b6eULL}, // 21 bytes; 
    {"cheat:c:ConvertCreatr click", 0xe13e862d2805a018ULL}, // 73 bytes;  ""
    {"cheat:a:CheatSwitchPlayer 4 ; c:ConvertCreatr click", 0x0459b6e27a742309ULL}, // 126 bytes;  ""
    {"cheat:c:StealSlab", 0xf7980bf5dcb9ea47ULL}, // 77 bytes;  ""
    {"cheat:c:StealSlab click", 0x511dd0cac558815eULL}, // 80 bytes;  ""
    {"cheat:a:CheatSwitchPlayer 1 ; c:StealSlab click", 0x41bbb2827484de4eULL}, // 119 bytes;  ""
    {"cheat:c:StealSlab click @40,40", 0xecf0c9cac558815eULL}, // 80 bytes;  ""
    {"cheat:c:LevelCreatureUp click", 0x3a42305f4ed1131dULL}, // 23 bytes; 
    {"cheat:c:LevelCreatureDown click", 0x6cd9f9e40c974ae7ULL}, // 31 bytes; 
    {"cheat:c:LevelCreatureUp click @40,40", 0x3407f43440405b6eULL}, // 21 bytes; 
    {"cheat:c:KillPlayer @HEART", 0x2bf46ad6d397a4a1ULL}, // 70 bytes;  ""
    {"cheat:c:KillPlayer click @HEART", 0xed0efa19ad8ad487ULL}, // 77 bytes;  ""
    {"cheat:c:KillPlayer click", 0xefb10419ad8ad487ULL}, // 77 bytes;  ""
    {"cheat:c:HeartHealth @HEART", 0xb612b4e743dee862ULL}, // 70 bytes;  "30000/30000"
    {"cheat:c:HeartHealth click @HEART", 0x91f6925955c40259ULL}, // 73 bytes;  "30000/30000"
    {"cheat:c:QueryAll", 0x78b6abb921862bd5ULL}, // 19 bytes; 
    {"cheat:c:QueryAll click", 0x6002945ec07c774eULL}, // 28 bytes; 
    {"cheat:c:CreatrInfoAll click", 0x786424b76cca56a1ULL}, // 27 bytes; 
    {"cheat:c:MkHappy click", 0x9ec83ee6478e1fb6ULL}, // 22 bytes; 
    {"cheat:c:MkAngry click", 0xa44141e6478e1fb6ULL}, // 22 bytes; 
    {"cheat:c:MkAngry click @40,40", 0x17fa363440405b6eULL}, // 21 bytes; 
    {"cheat:c:PlaceTerrain", 0x597e6d8b706cb633ULL}, // 77 bytes;  "Impenetrable Rock"
    {"cheat:a:CheatSwitchTerrain 12 ; c:PlaceTerrain click", 0xab4317e6ae726ab0ULL}, // 2256 bytes;  "Lava"
    {"cheat:a:CheatSwitchTerrain 11 ; c:PlaceTerrain click", 0xf406f17fd6241960ULL}, // 2230 bytes;  "Claimed area"
    {"cheat:c:DestroyThing", 0xf73e37b921862bd5ULL}, // 19 bytes; 
    {"cheat:c:DestroyThing click", 0xf1ef2b1c0a910da5ULL}, // 130 bytes; 
    {"cheat:c:DestroyThing click @HEART", 0xd69c6f11520bb005ULL}, // 89 bytes; 
    {"cheat:c:DestroyThing click @40,40", 0x5fe8fc3440405b6eULL}, // 21 bytes; 
    {"cheat:c:EditorPlaceTerrainRect press @120,125 ; c:EditorPlaceTerrainRect release", 0x7d5544df2f95a0a8ULL}, // 3937 bytes; 
    {"cheat:c:EditorRectClearEarth press @120,125 ; c:EditorRectClearEarth release", 0x47fa1eb2a3fb96b7ULL}, // 3964 bytes; 
    {"cheat:c:EditorRectDeleteThings press @120,125 ; c:EditorRectDeleteThings release", 0xe543ed074f2bf577ULL}, // 356 bytes; 
    {"cheat:c:EditorRectSetOwner press @120,125 ; c:EditorRectSetOwner release", 0xf32bd592389ee20cULL}, // 3284 bytes; 
    {"cheat:c:EditorFill click", 0xf2db02a012dea0f8ULL}, // 28 bytes; 
    {"cheat:c:EditorPlaceObject click", 0xd05aa08645a061d8ULL}, // 29 bytes; 
    {"cheat:c:EditorEyedropper click", 0xd726d9a012dea0f8ULL}, // 28 bytes; 
    {"cheat:c:EditorStamp click", 0x79c85da012dea0f8ULL}, // 28 bytes; 
    {"cheat:c:EditorQuery click", 0x0750cb8645a061d8ULL}, // 29 bytes; 
    {"cheat:c:EditorPlaceTrap click", 0x33db3f9eeead797fULL}, // 58 bytes; 
    {"cheat:c:EditorPlaceDoor click", 0x10d3dba012dea0f8ULL}, // 28 bytes; 
    {"cheat:c:EditorPlaceDoor click @ROOM", 0x231e90a012dea0f8ULL}, // 28 bytes; 
    {"cheat:multiplayer", 0xab912ab9e220e851ULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatRevealMap", 0xab912ab9e220e851ULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatWinLevel", 0xab912ab9e220e851ULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatAllRooms", 0xab912ab9e220e851ULL}, // 1 bytes; 
    {"cheat:multiplayer ; a:CheatMakeCreature 5 0", 0x4db612aa6fa2b4ffULL}, // 56 bytes; 
    {"cheat:multiplayer ; a:CheatPlaceTerrain 12 0", 0x4db612aa6fa2b4ffULL}, // 56 bytes; 
    {"cheat:multiplayer ; a:EditorUndo $C0", 0x4db612aa6fa2b4ffULL}, // 56 bytes; 
    {"cheat:multiplayer ; a:EditorRectClearEarth #120 #125", 0x4db612aa6fa2b4ffULL}, // 56 bytes; 
    {"cheat:multiplayer ; possess ; a:CheatKillCreature", 0xf88898ff72bb0862ULL}, // 35 bytes;  possess=1 ;
    {"cheat:multiplayer ; c:KillCreatr click", 0xd87ceb8ab0a56159ULL}, // 21 bytes; 
    {"cheat:multiplayer ; c:DestroyThing click @HEART", 0x0381e18ab0a56159ULL}, // 21 bytes; 
    {"cheat:multiplayer ; a:SetPlyrState 28 0", 0x4db612aa6fa2b4ffULL}, // 56 bytes; 
    {"cheat:a:SetPlyrState 28 0", 0x9b106cb921862bd5ULL}, // 19 bytes; 
    {"cheat:multiplayer ; a:SetPlyrState 2 1", 0x3059c7a1b5210785ULL}, // 28 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; a:EditorUndo $C0", 0x190372681a002d95ULL}, // 161 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; c:DestroyThing click", 0xf1ef2b1c0a910da5ULL}, // 130 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; a:EditorRectDeleteThings #120 #125", 0x641743791fd7e186ULL}, // 5784 bytes; 
    {"cheat:lua:function OnObjectDestroyed(t) PLAYER0.FLAG5 = 7 end ; a:EditorUndo $HEART", 0x5a7296f6143f618aULL}, // 119 bytes; 
