/******************************************************************************/
// Free implementation of Bullfrog's Dungeon Keeper strategy game.
/******************************************************************************/
/** @file editor_kfx_compat.h
 *     Whether a map loads in the KeeperFX release this game is compatible with.
 * @par Purpose:
 *     The editor's "Force KeeperFX" save writes KeeperFX's own map format and
 *     guarantees the result loads in that KeeperFX release (KFX 1.4 --
 *     docs/rebadge, decision D6): it refuses a map that uses anything only
 *     this game has -- level script commands, Lua functions, or base-game
 *     kinds (objects, traps, doors, creatures, effect generators, slabs) the
 *     release doesn't have. The list comes from kfx_compat_reference.inc,
 *     generated by scripts/gen_kfx_compat_reference.py.
 *     Kinds a campaign or level defines in its own configs ship with it, so
 *     they aren't this check's concern: only base-game kinds are checked.
 * @par  Copying and copyrights:
 *     This program is free software; you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation; either version 2 of the License, or
 *     (at your option) any later version.
 */
/******************************************************************************/
#ifndef DK_EDITOR_KFX_COMPAT_H
#define DK_EDITOR_KFX_COMPAT_H

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

struct MapContent;

/** The KeeperFX release the check is against, e.g. "KeeperFX 1.4.0". */
const char *editor_kfx_compat_reference_label(void);

/** Code name the game currently gives a kind ("object", "trap", "door", "creature",
 *  "effectgen" or "slab") at a model number -- lets tests supply their own. */
using EditorKindNameFn = std::function<std::string(const char *kind, int64_t model)>;

/** Everything in the map (script, Lua, things, slabs) the reference release can't
 *  load, one readable line each; empty when it loads there. */
std::vector<std::string> editor_kfx_compat_problems(const MapContent &content, const EditorKindNameFn &name_of);
/** Same, with the running game's own kind names (its loaded configs). */
std::vector<std::string> editor_kfx_compat_problems(const MapContent &content);

/** What the last editor_save_map() with EdSaveFmt_ForceKeeperFX refused over;
 *  empty when it wasn't refused for that reason. */
const std::vector<std::string> &editor_last_save_compat_problems(void);
void editor_set_last_save_compat_problems(const std::vector<std::string> &problems);

#endif
