#!/usr/bin/env python3
"""Writes src/kfx_editor/src/kfx_compat_reference.inc: what this game has that
the KeeperFX release it claims content compatibility with ("KFX 1.4",
build/make/version.mk) doesn't -- the list the in-game editor's
"Force KeeperFX" save checks a map against, so a map saved that way loads in
that KeeperFX release (docs/rebadge, decision D6):

  - level script commands and Lua API functions only this tree has
    (scripts/kfx_parity.py's "fork-only" list, against the release tag);
  - base-game kinds (objects, traps, doors, creatures, effect generators,
    slabs) in this tree's config/fxdata that the release doesn't have at the
    same model number -- map files store kinds by number.

    python3 scripts/gen_kfx_compat_reference.py            # vs v<KFX_COMPAT>.0, e.g. v1.4.0
    python3 scripts/gen_kfx_compat_reference.py --check    # exit 1 if the .inc is out of date
    python3 scripts/gen_kfx_compat_reference.py --upstream v1.5.0

Re-run it when KFX_COMPAT_* moves, after an upstream merge, and whenever
config/fxdata or the script/Lua tables change. Needs the release tag locally
(git fetch origin --tags).
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import kfx_parity as kp  # noqa: E402

ROOT = kp.REPO_ROOT
OUT = ROOT / "src/kfx_editor/src/kfx_compat_reference.inc"

# (kind tag used by the editor, fxdata file, how to read its names)
KIND_SOURCES = [
    ("object", "objects.cfg", ("block", "object")),
    ("trap", "trapdoor.cfg", ("block", "trap")),
    ("door", "trapdoor.cfg", ("block", "door")),
    ("slab", "terrain.cfg", ("block", "slab")),
    ("creature", "creature.cfg", ("creatures",)),
    ("effectgen", "effects.toml", ("block", "effectGenerator")),
]


def compat_tag() -> str:
    text = (ROOT / "build/make/version.mk").read_text()
    major = re.search(r"^KFX_COMPAT_MAJOR=(\d+)", text, re.M).group(1)
    minor = re.search(r"^KFX_COMPAT_MINOR=(\d+)", text, re.M).group(1)
    return f"v{major}.{minor}.0"


def kind_names(text: str, how: tuple) -> dict[int, str]:
    """Model number -> code name, as the game numbers them."""
    if how[0] == "creatures":
        m = re.search(r"^\s*Creatures\s*=\s*(.+)$", text, re.M | re.I)
        return {i: n.upper() for i, n in enumerate(m.group(1).split(), start=1)} if m else {}
    block = how[1]
    names, current = {}, None
    for line in text.splitlines():
        m = re.match(r"\s*\[(\w+?)(\d+)\]\s*$", line)
        if m:
            current = int(m.group(2)) if m.group(1).lower() == block.lower() else None
            continue
        m = re.match(r'\s*Name\s*=\s*"?([A-Za-z0-9_]+)"?', line, re.I)
        if current is not None and m:
            names[current] = m.group(1).upper()
    return names


def git_show(ref: str, path: str) -> str:
    return subprocess.run(["git", "-C", str(ROOT), "show", f"{ref}:{path}"], check=True,
                          capture_output=True, text=True).stdout


def fork_only_kinds(ref: str) -> list[tuple[str, int, str]]:
    out = []
    for kind, fname, how in KIND_SOURCES:
        ours = kind_names((ROOT / "config/fxdata" / fname).read_text(encoding="utf-8", errors="replace"), how)
        theirs = kind_names(git_show(ref, f"config/fxdata/{fname}"), how)
        for idx in sorted(ours):
            if theirs.get(idx) != ours[idx]:
                out.append((kind, idx, ours[idx]))
    return out


def fork_only_names(ref: str) -> tuple[list[str], list[str]]:
    upstream = kp.scan_sources(kp.read_ref(ref, kp.UPSTREAM_EXCLUDE), ref)
    ours = kp.scan_sources(kp.read_worktree(kp.OURS_EXCLUDE), "working tree")
    kp.canonicalise(upstream, ours)
    cats = kp.compare(upstream, ours)["categories"]
    commands = sorted({n for names in cats["script command"]["fork_only"].values() for n in names})
    lua = sorted({n for names in cats["lua"]["fork_only"].values() for n in names})
    return commands, lua


def c_list(names: list[str]) -> str:
    body = "".join(f'    "{n}",\n' for n in names)
    return f"{{\n{body}    nullptr,\n}}"


def render(ref: str) -> str:
    desc = kp.git("log", "-1", "--format=%h %cs", ref).strip()
    commands, lua = fork_only_names(ref)
    kinds = fork_only_kinds(ref)
    label = "KeeperFX " + ref.lstrip("v")
    kind_rows = "".join(f'    {{"{k}", {i}, "{n}"}},\n' for k, i, n in kinds)
    return f"""// Generated by scripts/gen_kfx_compat_reference.py --upstream {ref} ({desc}).
// Don't edit: re-run the script (see its docstring for when).
// What this game has that {label} doesn't -- the "Force KeeperFX" save
// refuses a map that uses any of it (editor_kfx_compat.cpp).

#define KFX_COMPAT_REFERENCE_LABEL "{label}"

// Level script commands (and script subfunctions) {label} doesn't know.
static const char *const kfx_ref_forkonly_script_commands[] = {c_list(commands)};

// Lua API functions and methods {label} doesn't have.
static const char *const kfx_ref_forkonly_lua_functions[] = {c_list(lua)};

// Base-game kinds (config/fxdata) {label} doesn't have at this model number.
struct KfxRefForkOnlyKind {{ const char *kind; int64_t index; const char *name; }};
static const struct KfxRefForkOnlyKind kfx_ref_forkonly_kinds[] = {{
{kind_rows}    {{nullptr, 0, nullptr}},
}};
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--upstream", default=None, help="release tag to check against (default: v<KFX_COMPAT>.0)")
    ap.add_argument("--check", action="store_true", help="exit 1 if the .inc is out of date")
    args = ap.parse_args()
    ref = args.upstream or compat_tag()
    try:
        text = render(ref)
    except subprocess.CalledProcessError as e:
        sys.stderr.write(f"git failed ({' '.join(e.cmd)}): {e.stderr}\nIs the tag fetched? git fetch origin --tags\n")
        return 2
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            sys.stderr.write(f"{OUT.relative_to(ROOT)} is out of date; run scripts/gen_kfx_compat_reference.py\n")
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} against {ref}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
